### ISSUE TITLE
ui_ColorChooserButton.h missing and assert import

### ISSUE THREAD

**Issue by macpod** [BatchDrake/SuWidgets#1]
Hi, I believe ui_ColorChooserButton.h is missing from this repository. I also believe <assert.h> includes should be added to Transition.h and Constellation.h

This looks like a neat project!

**Comment by BatchDrake** [comment]
Hey, thank you very much for your feedback. This file should be generated
by uic on ColorChooserButton.ui after calling qmake. Which version of qmake
are you using?

I'll review the assert.h issue ASAP.

**Comment by macpod** [comment]
Ah, I haven't worked much with QT. I'm aware you reference QT 5.11. Linux Mint 19 (Ubuntu 18.04LTS) repos have qt 5.9.5/qmake 3.1:
$ qmake --version
QMake version 3.1
Using Qt version 5.9.5 in /usr/lib/x86_64-linux-gnu

Didn't think that would make a diff but perhaps that's juts it

**Comment by BatchDrake** [comment]
My bad, I forgot to add ColorChooserButton.ui to the .pri file, it should be working now. I also included assert.h in the cpp files for Transition and Constellation, could you try again?

**Comment by macpod** [comment]
I deleted/re-checked out SuWidgets. This time it compiled successfully. Thank you
