### ISSUE TITLE
Make errors on Raspberry Pi 4 — x,y,z "was not declared in this scope"

### ISSUE THREAD

**Issue by peterjdann** [BatchDrake/SuWidgets#19]
Have been attempting to build SuWidgets as part of trying to build SigDigger, as per https://github.com/BatchDrake/SigDigger

I am hitting the following errors when trying to make SuWidgets:

GLWaterfall.cpp:294:12: error: ‘GL_LINE_SMOOTH’ was not declared in this scope; did you mean ‘GL_LINE_WIDTH’?
  294 |   glEnable(GL_LINE_SMOOTH);
      |            ^~~~~~~~~~~~~~
      |            GL_LINE_WIDTH
GLWaterfall.cpp:295:10: error: ‘GL_LINE_SMOOTH_HINT’ was not declared in this scope
  295 |   glHint(GL_LINE_SMOOTH_HINT, GL_NICEST);
      |          ^~~~~~~~~~~~~~~~~~~
GLWaterfall.cpp:296:12: error: ‘GL_POINT_SMOOTH’ was not declared in this scope
  296 |   glEnable(GL_POINT_SMOOTH);
      |            ^~~~~~~~~~~~~~~
GLWaterfall.cpp:297:10: error: ‘GL_POINT_SMOOTH_HINT’ was not declared in this scope
  297 |   glHint(GL_POINT_SMOOTH_HINT, GL_NICEST);
      |          ^~~~~~~~~~~~~~~~~~~~
GLWaterfall.cpp: In member function ‘void GLWaterfallOpenGLContext::render(int, int, int, int, float, float)’:
GLWaterfall.cpp:636:16: error: ‘GL_ALL_ATTRIB_BITS’ was not declared in this scope; did you mean ‘GL_ALL_BARRIER_BITS’?
  636 |   glPushAttrib(GL_ALL_ATTRIB_BITS); // IMPORTANT TO PREVENT CONFLICTS WITH QPAINTER
      |                ^~~~~~~~~~~~~~~~~~
      |                GL_ALL_BARRIER_BITS
GLWaterfall.cpp:636:3: error: ‘glPushAttrib’ was not declared in this scope
  636 |   glPushAttrib(GL_ALL_ATTRIB_BITS); // IMPORTANT TO PREVENT CONFLICTS WITH QPAINTER
      |   ^~~~~~~~~~~~
GLWaterfall.cpp:642:3: error: ‘glLoadIdentity’ was not declared in this scope
  642 |   glLoadIdentity();
      |   ^~~~~~~~~~~~~~
GLWaterfall.cpp:703:3: error: ‘glPopAttrib’ was not declared in this scope
  703 |   glPopAttrib();

**Comment by BatchDrake** [comment]
This looks like a broken Qt install, maybe? QMake should check for OpenGL libraries/headers right before the build. Did `qmake` produce any error message? What operating system are you using?

In any case, try again installing the following packages:

```
$ sudo apt install mesa-common-dev libgl1-mesa-dev
```

**Comment by peterjdann** [comment]
Thank you very much for such a speedy reply!

I have tried several ways of installing Qt, and perhaps these are now in conflict?

Most recently, I used the approach described here: https://linuxhint.com/install-qt-creator-raspberry-pi/

I am running

Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

Raspberry Pi 4.

I have run the command you suggested.

qmake generates no error messages or visible output of any kind.

The problem, unfortunately, persists.

With kind regards,

Peter Dann

**Comment by BatchDrake** [comment]
In that case, yes. This looks a lot like you have conflicting installs
somehow, and while one thinks it has all its dependencies in check, the
produced Makefiles are basically useless.

My suggestion is, you delete all the generated Makefiles in SuWidgets, and
run qmake from one of those installs, specifying the full path of the qmake
executable, wherever your install is.

Also, I would like to know the full compiler command, as printed to the
terminal. Maybe we can figure out where is it looking for OpenGL headers,
and why.

Cheers,

**Comment by peterjdann** [comment]
Thank you for these suggestions. I have tried to follow your suggestions to the best of my (not wonderful) ability, but so far without success.

I have cleared existing makefiles from the SuWidgets directory, and run qmake using a full path to the result of ‘which qmake’.

So, I have been executing:
sudo /usr/bin/qmake /usr/src/SuWidgets/SuWidgetsLib.pro

Result has been "Info: creating stash file /usr/src/SuWidgets/.qmake.stash”

When I then run ’sudo make’, the result is as before:

*****

g++ -c -pipe -O2 -std=gnu++1y -Wall -Wextra -D_REENTRANT -fPIC -D_SU_SINGLE_PRECISION -DHAVE_VOLK=1 -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../local/include/sigutils -I../../local/include/sigutils/util -I../../local/include -I../../include/arm-linux-gnueabihf/qt5 -I../../include/arm-linux-gnueabihf/qt5/QtOpenGL -I../../include/arm-linux-gnueabihf/qt5/QtWidgets -I../../include/arm-linux-gnueabihf/qt5/QtGui -I../../include/arm-linux-gnueabihf/qt5/QtCore -Irelease -I. -I../../lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -o release/GLWaterfall.o GLWaterfall.cpp
GLWaterfall.cpp: In member function ‘void GLWaterfallOpenGLContext::initialize()’:
GLWaterfall.cpp:292:12: error: ‘GL_MULTISAMPLE’ was not declared in this scope; did you mean ‘GL_MULTISAMPLES_NV’?
  292 |   glEnable(GL_MULTISAMPLE);
      |            ^~~~~~~~~~~~~~
      |            GL_MULTISAMPLES_NV
GLWaterfall.cpp:294:12: error: ‘GL_LINE_SMOOTH’ was not declared in this scope; did you mean ‘GL_LINE_WIDTH’?
  294 |   glEnable(GL_LINE_SMOOTH);
      |            ^~~~~~~~~~~~~~
      |            GL_LINE_WIDTH
GLWaterfall.cpp:295:10: error: ‘GL_LINE_SMOOTH_HINT’ was not declared in this scope
  295 |   glHint(GL_LINE_SMOOTH_HINT, GL_NICEST);
      |          ^~~~~~~~~~~~~~~~~~~
GLWaterfall.cpp:296:12: error: ‘GL_POINT_SMOOTH’ was not declared in this scope
  296 |   glEnable(GL_POINT_SMOOTH);
      |            ^~~~~~~~~~~~~~~
GLWaterfall.cpp:297:10: error: ‘GL_POINT_SMOOTH_HINT’ was not declared in this scope
  297 |   glHint(GL_POINT_SMOOTH_HINT, GL_NICEST);
      |          ^~~~~~~~~~~~~~~~~~~~
GLWaterfall.cpp: In member function ‘void GLWaterfallOpenGLContext::render(int, int, int, int, float, float)’:
GLWaterfall.cpp:636:16: error: ‘GL_ALL_ATTRIB_BITS’ was not declared in this scope; did you mean ‘GL_ALL_BARRIER_BITS’?
  636 |   glPushAttrib(GL_ALL_ATTRIB_BITS); // IMPORTANT TO PREVENT CONFLICTS WITH QPAINTER
      |                ^~~~~~~~~~~~~~~~~~
      |                GL_ALL_BARRIER_BITS
GLWaterfall.cpp:636:3: error: ‘glPushAttrib’ was not declared in this scope
  636 |   glPushAttrib(GL_ALL_ATTRIB_BITS); // IMPORTANT TO PREVENT CONFLICTS WITH QPAINTER
      |   ^~~~~~~~~~~~
GLWaterfall.cpp:642:3: error: ‘glLoadIdentity’ was not declared in this scope
  642 |   glLoadIdentity();
      |   ^~~~~~~~~~~~~~
GLWaterfall.cpp:703:3: error: ‘glPopAttrib’ was not declared in this scope
  703 |   glPopAttrib();
      |   ^~~~~~~~~~~
make[1]: *** [Makefile.Release:5603: release/GLWaterfall.o] Error 1
make[1]: Leaving directory '/usr/src/SuWidgets'
make: *** [Makefile:42: release] Error 2

*****

It appears that on my Raspberry Pi the headers the compiler needs to be able to find, are in /usr/include/arm-linux-gnueabihf/qt5/QtGui

Here is a small sample of the files in that directory.

QAbstractTextDocumentLayout         QOpenGLFunctions_4_2_Compatibility
QAbstractUndoItem                   QOpenGLFunctions_4_2_Core
QAccessible                         QOpenGLFunctions_4_3_Compatibility
QAccessibleActionInterface          QOpenGLFunctions_4_3_Core
QAccessibleApplication              QOpenGLFunctions_4_4_Compatibility


`gcc -print-prog-name=cpp` -v gives the following result:

Using built-in specs.
COLLECT_GCC=cpp
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 10.2.1-6+rpi1' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=arm-linux-gnueabihf- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --disable-libquadmath-support --enable-plugin --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --disable-werror --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20210110 (Raspbian 10.2.1-6+rpi1) 
COLLECT_GCC_OPTIONS='-E' '-v'  '-mfloat-abi=hard' '-mfpu=vfp' '-mtls-dialect=gnu' '-marm' '-march=armv6+fp'
 /usr/lib/gcc/arm-linux-gnueabihf/10/cc1 -E -quiet -v -imultilib . -imultiarch arm-linux-gnueabihf - -mfloat-abi=hard -mfpu=vfp -mtls-dialect=gnu -marm -march=armv6+fp
ignoring nonexistent directory "/usr/local/include/arm-linux-gnueabihf"
ignoring nonexistent directory "/usr/lib/gcc/arm-linux-gnueabihf/10/include-fixed"
ignoring nonexistent directory "/usr/lib/gcc/arm-linux-gnueabihf/10/../../../../arm-linux-gnueabihf/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/arm-linux-gnueabihf/10/include
 /usr/local/include
 /usr/include/arm-linux-gnueabihf
 /usr/include
End of search list.

So, it looks like the headers the compiler needs to find are two subdirectories below one of the directories that is in the compiler's search path (ie, two subdirectories below /usr/include/arm-linux-gnueabihf)

I’d appreciate any further suggestions you might have on how to solve this problem.

With best wishes,

Peter Dann

**Comment by BatchDrake** [comment]
Okay, I've been looking into it more thoroughly. Those "not declared in this scope" errors refers to stuff that is not available in your OpenGL API. Raspberry Pi uses OpenGL ES (which is like a reduced version of OpenGL) which is, in many cases, fundamentally incompatible with OpenGL. One of the things it does not support is precisely that, `GL_ALL_ATTRIB_BITS`.

Still, I am not too happy with this explanation. I _know_ some people built SigDigger regularly in Raspberry Pi, and they even showed me screenshots of it. I am still asking around, I'll get back to you ASAP.

**Comment by peterjdann** [comment]
Thank you!

Peter Dann

**Comment by BatchDrake** [comment]
Hi again,

Just asked again, and people tell me that they were able to run SigDigger under Raspberry Pi 4 without much issues.

My bet is there is something extremely broken with your Qt install, that makes QMake build SuWidgets with OpenGL ES headers (which are not going to work). Now that we see that Qt 5 is not working, I suggest you install Qt 6 instead and use qmake6 for building both SuWidgets and SigDigger.

**Comment by peterjdann** [comment]
Thanks Gonzalo. The problem is clearly at my end!

Unfortunately, suggestions like “install Qt 6” don’t mean as much to me as they do to you.I found a tutorial here that I’ll try working through.

I did manage to “build” SigDigger successfully after doing a complete fresh install of my Raspberry Pi operating system, and then using the script you provided at https://batchdrake.github.io/SigDigger/ (after changing the reference in the script from “example.com <http://example.com/>” to a real URL), but when I ran it, I got “qt.qpa.xcb: QXcbConnection: XCB error: 148 (Unknown)”, a nice splash window with your name on it, and then a window displaying some frequency calibration points around 437M — but no means of navigating anything, no widgets, nothing else. That was using was I thought was Qt 5, but this is clearly a separate problem from my original report.

Guess I’ll try a fresh Raspberry Pi install from scratch and see if I can install Qt 6 and see if that resolves these issues. This is quite challenging for a relatively elderly novice — but I’ve appreciated your efforts to assist. Thank you.

With best wishes,

Peter Dann

**Comment by BatchDrake** [comment]
This is weird. Can you share a screenshot of what you see exactly?

**Comment by peterjdann** [comment]
I’m running VNC on a Mac. The normal “take a screenshot” facility on Mac doesn’t seem to work when VNC is in the foreground, so I took this photo of my Mac screen with my phone.

Regards,

Peter

￼

**Comment by peterjdann** [comment]
Sorry, I really am a complete idiot!

All I needed to do was increase my screen resolution for VNC settings in Raspberry Pi (a lot) and now I can see the whole SigDigger GUI. Wonderful! Now to play…

With best wishes,

Peter Dann

> Begin forwarded message:
> 
> From: Peter Dann ***@***.***>
> Subject: Re: [BatchDrake/SuWidgets] Make errors on Raspberry Pi 4 — x,y,z "was not declared in this scope" (Issue #19)
> Date: 11 April 2023 at 8:58:05 pm AEST
> To: BatchDrake/SuWidgets ***@***.***>
> 
> I’m running VNC on a Mac. The normal “take a screenshot” facility on Mac doesn’t seem to work when VNC is in the foreground, so I took this photo of my Mac screen with my phone.
> 
> Regards,
> 
> Peter
> 
> <Taken with my iPhone.png>
>

**Comment by BatchDrake** [comment]
I am afraid I am not seeing anything, maybe macOS screwed up with the drag and drop. Could you attach the screenshot again?

**Comment by BatchDrake** [comment]
Ah haha okay, congratulations then! :D

 I'm closing this issue for now, feel free to open a new one if something else comes up

**Comment by peterjdann** [comment]
Hi Gonzalo,

I have solved my problem. I had the wrong screen resolution settings in my Raspberry Pi for my VNC connection. The screen resolution was too small. When I made the screen resolution settings for VNC as large as possible, I can see your beautiful application just how it is meant to look. So your build/install script worked for me very well!

With many thanks,

Peter
