### ISSUE TITLE
Where is 'I' defined?

### ISSUE THREAD

**Issue by stevecrozz** [BatchDrake/SuWidgets#21]
Where should this value 'I' be coming from? Can't see how to fix this.

~~~
$ make
make -f Makefile.Release
make[1]: Entering directory '/home/stevecrozz/dev/SuWidgets'
g++ -c -pipe -O2 -std=gnu++1y -Wall -Wextra -D_REENTRANT -fPIC -D_SU_SINGLE_PRECISION -DHAVE_VOLK -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -Irelease -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o release/Constellation.o Constellation.cpp
In file included from Constellation.h:28,
                 from Constellation.cpp:21:
Constellation.cpp: In member function ‘void Constellation::drawAxes()’:
Constellation.cpp:101:32: error: ‘I’ was not declared in this scope; did you mean ‘PI’?
  101 |     SUCOMPLEX delta = SU_C_EXP(I * angle);
      |                                ^
make[1]: *** [Makefile.Release:538: release/Constellation.o] Error 1
make[1]: Leaving directory '/home/stevecrozz/dev/SuWidgets'
make: *** [Makefile:42: release] Error 2
~~~

**Comment by BatchDrake** [comment]
In sigutils. How are you building SuWidgets exactly? This should work in
virtually any system.

**Comment by stevecrozz** [comment]
I was following along with:
https://github.com/BatchDrake/SigDigger#how-am-i-supposed-to-compile-this

My system is a:
~~~
$ uname -a
Linux stevecrozz-ThinkPad-T450s 5.19.0-38-generic #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 17:33:16 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.10
DISTRIB_CODENAME=kinetic
DISTRIB_DESCRIPTION="Ubuntu 22.10"
~~~

**Comment by BatchDrake** [comment]
My bet is that you are either mixing up older versions or different
branches. Is this a build from master or develop? How did you build
Sigutils and Suscan?

I have a script named blsd (https://actinid.org/blsd) that does all the
build steps automatically for you, and it does not even require super-user
privileges. You just give it executable permissions and run it from
terminal. If the build goes successfully, you end up with a directory
containing SigDigger along with all its dependencies that you can place
anywhere you want and run directly from terminal. Give it a try.

Cheers,

**Comment by stevecrozz** [comment]
Thank you. This script was very helpful and I was able to successfully build SigDigger.
