### ISSUE TITLE
Compile-errors on "develop" on macOS

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/SuWidgets#3]
Hey
New changes in the `develop` branch break compiling on macOS.
After `qmake SuWidgets.pro` and `make`, I get this error:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
```

Then I added `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include` as an additional include directory to Makefile which solved that error but introduced new errors for cmath. Some examples:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:330:9: error:
      no member named 'isunordered' in the global namespace
```

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:318:9: error:
      no member named 'signbit' in the global namespace
```

**Comment by mehdideveloper** [comment]
FYI I managed to compile this on the other laptop!
Let me know what you need to know from both laptops (like version info, library path info, etc) to troubleshoot this

**Comment by BatchDrake** [comment]
Mmmh, these errors don't seem to be related to anything inside SuWidgets. Do you have the whole build log?

**Comment by mehdideveloper** [comment]
I afraid not. I will try again and this time will not clean. Which files are you interested in?

**Comment by BatchDrake** [comment]
Problem is, I don't know yet :/ These errors are happening inside Xcode's headers, and I'd need to see where these files are being referenced from.

**Comment by mehdideveloper** [comment]
So I am not sure what exactly causes these issues, but apparently there's mismatch between Xcode's libraries and other C++ standard libraries. I didn't investigate further. I just uninstalled Xcode and then ran this command to fix the installation path and then built SuWidgets on this machine:
`sudo xcode-select --switch /Library/Developer/CommandLineTools`

**Comment by BatchDrake** [comment]
I had these issues in the Mac Mini too. In the end, the only thing I had to do was to run make clean, remove qmake's stash files and rebuild from scratch. Can't point out the exact cause though.
