### ISSUE TITLE
Invalid operands compile error on macOS

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/SuWidgets#4]
In this line:
https://github.com/BatchDrake/SuWidgets/blob/3b9e4996617b813daa43f61916d34c6a5bfc57e4/Waveform.cpp#L959

you are multiplying a `std::complex<float>` (which is `I`) with a `double` and it throws a compile error! 
Can you for example do something like `SU_C_IMAG(I) * (M_PI * i)` instead?

**Comment by BatchDrake** [comment]
Try replacing it by ``` this->data.feed(SU_ASFLOAT(.75) * SU_C_EXP(I * SU_ASFLOAT((M_PI * i) / 64))); ``` and tell me whether it works.

**Comment by mehdideveloper** [comment]
Yes it fixed the error. I have another more strange error, but will create another issue as it's not related to this one

**Comment by mehdideveloper** [comment]
Actually I'm not sure if I should've closed this issue. Please reopen it if you need it for your reminder to fix

**Comment by BatchDrake** [comment]
Same, changes are in `feature/timeview` now.

**Comment by mehdideveloper** [comment]
This compiles now. I still have that link error because of an empty `-l` which I have to manually delete from different Makefiles. Other than that, there are no build issues
