### ISSUE TITLE
Invalid operand types compile error on macOS

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/SuWidgets#5]
I get assert error on compile for this line:

https://github.com/BatchDrake/SuWidgets/blob/3b9e4996617b813daa43f61916d34c6a5bfc57e4/Waveform.cpp#L429

```
In file included from Waveform.cpp:19:
In file included from ./Waveform.h:25:
In file included from /usr/local/include/sigutils/sigutils/types.h:26:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/math.h:999:5: error: static_assert failed due to requirement '!(std::is_same<double, double>::value && std::is_same<double, double>::value)' ""
    static_assert((!(std::is_same<_A1, __result_type>::value &&
    ^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Waveform.cpp:429:23: note: in instantiation of function template specialization 'pow<double, double>' requested here
  qreal amount = std::pow<qreal>(1.1, -event->delta() / 120.);
```

**Comment by BatchDrake** [comment]
Just fixed it, try it out!

**Comment by mehdideveloper** [comment]
Hmmmm. I missed your reply!
It's still not fixed for me !
(Installed the latest sigutils and suscan from `develop` and also SuWidgets from `feature/timeview` but still get the same exact error!
I also checked `types.h` in sigutils (in both master and develop) and the last change was made 4 months ago 🤔

**Comment by BatchDrake** [comment]
Weird. I've been building just fine these days. I'll check as soon as I get
home (4h from now).

**Comment by mehdideveloper** [comment]
Your change basically means the same condition as before. The `static_assert` in the `math` library complains about the two operands of the `pow` being of the same type and you're making sure that happens (bring a `qreal` to a power of another `qreal` value and return a `qreal`). This is the actual code of that assert:

```
pow(_A1 __lcpp_x, _A2 __lcpp_y) _NOEXCEPT
{
    typedef typename std::__promote<_A1, _A2>::type __result_type;
    static_assert((!(std::is_same<_A1, __result_type>::value &&
                     std::is_same<_A2, __result_type>::value)), "");
    return ::pow((__result_type)__lcpp_x, (__result_type)__lcpp_y);
}
```

The exclamation mark in the assert seems to cause the problem. For example if I change the first value to `float` it compiles, but not when both operands are qreal or double.
Am I missing something here? Is it expected, or a special thing in macOS C++ libraries?

Also found this:
http://lists.llvm.org/pipermail/llvm-bugs/2015-February/038402.html

**Comment by BatchDrake** [comment]
I went through that thread before. In the end the problem was overspecifying the template types by hand (which is absolutely nonstandard, see https://es.cppreference.com/w/cpp/numeric/math/pow). This was fixed in `develop` back when I was merging everything back to it.

Maybe this is a good time to reconsider the workflow: don't merge back to develop unless we're sure it will build both in MacOS and GNU/Linux.

**Comment by mehdideveloper** [comment]
Is this fixed in the recent changes?! Because I still face this error trying to build the latest (from feature/ux-improvements)
on Waveform.cpp:443

**Comment by BatchDrake** [comment]
I branched from a nonupdated version of develop, everything is working again.

**Comment by mehdideveloper** [comment]
I can confirm that this is fixed in feature/ux-improvements on macOS 👍
